openapi: 3.1.0
info:
  title: RouteHub REST API
  description: RouteHub is a user-friendly API designed to serve as a central access point for clients seeking efficient routes planning.
  version: 0.8.0
  license:
    name: GNU Affero General Public License
    url: https://www.gnu.org/licenses/agpl-3.0.html

servers:
  - url: http://www.routehub.com:3000

components:
  securitySchemes:
    bearerJWT:
      description: "A JSON Web Token (JWT) sent in the `Authorization` header, prefixed by the word `Bearer`. For example: `Authorization: Bearer <JWT>`"
      type: http
      scheme: bearer
      bearerFormat: JWT

# Enforce security policies at a global level
security:
  - bearerJWT: []

paths:

  /vehicles:      { $ref: "routehub/vehicles.yaml#/paths/~1vehicles" }
  /vehicles/{id}: { $ref: "routehub/vehicles.yaml#/paths/~1vehicles~1{id}" }

  /fleets:      { $ref: "routehub/fleets.yaml#/paths/~1fleets" }
  /fleets/{id}: { $ref: "routehub/fleets.yaml#/paths/~1fleets~1{id}" }

  /drivers:      { $ref: "routehub/drivers.yaml#/paths/~1drivers" }
  /drivers/{id}: { $ref: "routehub/drivers.yaml#/paths/~1drivers~1{id}" }

  /milestones:      { $ref: "routehub/milestones.yaml#/paths/~1milestones" }
  /milestones/{id}: { $ref: "routehub/milestones.yaml#/paths/~1milestones~1{id}" }

  /deliveries:      { $ref: "routehub/deliveries.yaml#/paths/~1deliveries" }
  /deliveries/{id}: { $ref: "routehub/deliveries.yaml#/paths/~1deliveries~1{id}" }

  /lots:           { $ref: "routehub/delivery-lots.yaml#/paths/~1lots" }
  /lots/{id}:      { $ref: "routehub/delivery-lots.yaml#/paths/~1lots~1{id}" }
  /lots/{id}/plan: { $ref: "routehub/delivery-lots.yaml#/paths/~1lots~1{id}~1plan" }
